# Required
github_username: "username"
github_password: "your_password"

# Optional (comment out if not using)
# github_totp_seed: "ABCDEF1234567890" # Obtained via https://github.com/settings/security